# Add Homebrew `/usr/local/bin` and User `~/bin` to the `$PATH`
PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=$HOME/bin:$PATH

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,bashrc,exports,aliases,functions,extra}; do
  [ -r "$file" ] && source "$file"
done
unset file

# Load script to autocomplete git branch names
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# export ANDROID_HOME=$HOME/Library/Android/sdk
# export JAVA_HOME=$(/usr/libexec/java_home)
# export PATH=$PATH:$ANDROID_HOME/tools
# export PATH=$PATH:$ANDROID_HOME/platform-tools
# export PATH="$HOME/.fastlane/bin:$PATH"

# For rbenv
eval "$(rbenv init -)"

# For pyenv
if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi

# For virtualenv
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

export PATH
