# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
  [ -r "$file" ] && source "$file"
done
unset file

# Load script to autocomplete git branch names
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# For Postgresql
export PGDATA='/usr/local/var/postgres'
export PGHOST=localhost

# For Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# For virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh

# For nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# For Travis
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

export PATH
