# Add Homebrew `/usr/local/bin` and User `~/bin` to the `$PATH`
PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=$HOME/bin:$PATH

# export ANDROID_HOME=$HOME/Library/Android/sdk
# export JAVA_HOME=$(/usr/libexec/java_home)
# export PATH=$PATH:$ANDROID_HOME/tools
# export PATH=$PATH:$ANDROID_HOME/platform-tools
# export PATH="$HOME/.fastlane/bin:$PATH"

export GPG_TTY=$(tty)
export PATH

source ~/.bashrc
