# Added by Postgresql
export PGDATA='/usr/local/var/postgres'
export PGHOST=localhost

# Added by Travis
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Add RVM to PATH for scripting. 
PATH="$PATH:$HOME/.rvm/bin"

export PATH
