# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
  [ -r "$file" ] && source "$file"
done
unset file

# Load script to autocomplete git branch names
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# For Postgresql
export PGDATA='/usr/local/var/postgres'
export PGHOST=localhost

# For Travis
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

# For Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# For Volta
export VOLTA_HOME="/Users/leedongwei/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Turn on pyenv
eval "$(pyenv init -)"

# For direnv
eval "$(direnv hook bash)"

export PATH
